name: Deploy page

on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  site:
    name: Generate Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Generate site
        run: "nix-shell --run generate"

      - name: Publish site
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
